<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AwesomeAssertions" />
        <PackageReference Include="Grpc.AspNetCore" />
        <PackageReference Include="protobuf-net.Grpc" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="System.Security.Cryptography.Xml" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Codify.GrpcCodeFirstDataAnnotations.Exceptions\Codify.GrpcCodeFirstDataAnnotations.Exceptions.csproj" />
      <ProjectReference Include="..\Codify.GrpcCodeFirstDataAnnotations.TestServer\Codify.GrpcCodeFirstDataAnnotations.TestServer.csproj" />
    </ItemGroup>

</Project>