<Project>

  <PropertyGroup>
    <Authors>Andy van Stokkum</Authors>
    <Company>Codify</Company>
    <Version>1.0.0</Version>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <FileVersion>$(Version)</FileVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageProjectUrl>https://github.com/andyvans/GrpcCodeFirstDataAnnotations</PackageProjectUrl>
    <RepositoryUrl>https://github.com/andyvans/GrpcCodeFirstDataAnnotations</RepositoryUrl>
    <PackageLicenseFile>license.txt</PackageLicenseFile>
    <PackageIcon>codify.png</PackageIcon>
    <PackageIconUrl />
    <PackageTags>grpc;code-first;data-annotations;validation</PackageTags>
  </PropertyGroup>

</Project>
